### PR TITLE
Adding I24 power data

### PR DESCRIPTION
**Pull request by Baaleos**
In reference to https://github.com/Segs/Segs/issues/732
Here is the I24 power data jsons

### CODE REVIEW

**Comment by Baaleos** [comment]
@broxen or @cyanpill  / @segs-community 
PR for review / merge when ready.
I think from the discussions we agreed that the data is probably best in its granular form initially - one json per power, but then an intermediary process will merge JSON's based on powerset and then transform into the BIN format for use in servers.

**Comment by cyanpill** [comment]
My concern is that the variable names are all different from what we are using now in https://github.com/Segs/Segs/blob/develop/Projects/CoX/Common/GameData/power_serializers.cpp

Could you redo the data with different names? For example, this is what i24 blaster assault rifle should look like: https://pastebin.com/m3e9TKHG

**Comment by Baaleos** [comment]
Where did this model come from? Once I understand the source of the model and the variable names/convention I can properly adapt. The data I uploaded comes from Mids Hero Designer distributed database files.

**Comment by Baaleos** [comment]
Ah- it’s a custom model made for Segs?

**Comment by cyanpill** [comment]
I believe it's based on the contents of powers.bin. I guess Mids choose different names for some reason.

**Comment by cyanpill** [comment]
With some more testing on importing from json, I'm confident I can import this power data for effects. However this data is missing information for FX and icons and maybe more stuff. The power.json created from the issue 1 powers.bin does have those, so it should work to copy just the effect section for each power we have as of issue 1.

**Pull request merged**
